version: "3.7"

networks:
  smtpot:
    name: smtpot

services:
  server:
    build: ./docker
    container_name: smtpot
    env_file: ./.env
    working_dir: /app
    volumes:
      - .:/app:cached
    networks:
      - smtpot
    ports:
      - "${SMTP_PORT}:25"
